/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:5d88a9b9-2aca-43d8-8e94-506333241787",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_esBWUYLHR",
    "aws_user_pools_web_client_id": "57alae8ivejrfon06i1tk4ecu3",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://mnoqpxh235.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://baqaax27xjezlb6q76gzozloz4.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "geo": {
        "amazon_location_service": {
            "region": "ap-southeast-1",
            "maps": {
                "items": {
                    "mapa593c7f1-dev": {
                        "style": "VectorEsriStreets"
                    },
                    "map0201b93a-dev": {
                        "style": "VectorHereExplore"
                    }
                },
                "default": "map0201b93a-dev"
            },
            "geofenceCollections": {
                "items": [
                    "geofenceCollection5beedbf0-dev",
                    "MyGeoCollection"
                ],
                "default": "MyGeoCollection"
            }
        }
    }
};


export default awsmobile;
